name: "veracode-generate-binary"
description: "Prepare binary to be analyzed"
inputs:
  cache_key:
    required: true
    description: key used to identify the cache

runs:
  using: "composite"
  steps:
#    - name: Exclude development files
#      run: |
#        if [[ -f ".veracode-exclusions" ]]; then
#          for LINE in $( cat .veracode-exclusions | sed 's/[^a-zA-Z0-9_./-]//g' | sed -r 's/\.\./\./g' ); do
#            if [[ -d "$LINE" ]]; then
#              rm -rf "$LINE"
#              echo "[INFO] - folder removed from analysis : '$LINE'"
#            elif [[ -e "$LINE" ]]; then
#              rm -f "$LINE"
#              echo "[INFO] - file removed from analysis : '$LINE'"
#            elif [[ -z "$LINE" ]]; then
#              echo "[INFO] - empty directive. Skipping this line"
#            else
#              echo "[INFO] - target to exclude not found. Skipping: '$LINE'"
#            fi
#          done
#        else
#          echo "[INFO] - No '.veracode-exclusions' file found for this module. Skipping exclusion step"
#        fi
#      shell: bash

    - name: install ant
      run : |
        sudo apt update
        sudo apt install -y ant
      shell: bash

    - name: Set up JDK 1.8
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Build war with Ant
      run: |
        cd etc/build
        ant war
      shell: bash

    - name: Create zip file
      run: |
        if [[ -z "${{ inputs.cache_key }}" ]]; then
          echo "[DEBUG] - cache key is missing. killing process"
          exit 1
        fi
        zip -rq "${{ inputs.cache_key }}.zip" *
      shell: bash

    - uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: "${{ inputs.cache_key }}.zip"
        key: ${{ inputs.cache_key }}
